Add a --fast-deps option to `comfy install/reintstall` that enables new faster/unified/uv-based dependency install
Comfy-Org/comfy-cli pull request #141
Opened 2024-07-26 17:08 UTC by telamonian

This PR adds a new option `--fast-deps`, to `comfy install` and `comfy reinstall`. This option enables the new dependency handling implementation. The features of said new dependency handling currently cover:

- Uses uv to install all Python deps (very fast)
- Resolves all core and custom extension dependencies together
  - Any conflicts between core and extensions are settled in core's favor
  - TODO: extension-vs-extension dependency conflict handling
- Minimizes total number of subprocess calls to external Python dependency-handling tools

2024-08-02 18:49 UTC, telamonian commented
Okay, the code in this PR is coming along. Fixed a bunch of bugs/problems, and thanks to #147 this PR is now much easier to test out for yourself. Just install this PR branch, then do:

```bash
comfy install --fast-deps --manager-url=https://github.com/ltdrdata/ComfyUI-Manager.git@feat/cnr
```

specifying any other args as normal. The fast-deps option will now also work with installing custom nodes, eg:

```bash
comfy node install --fast-deps comfyui-kjnodes comfyui-animatediff-evolved
```

2024-08-09 12:58 UTC, telamonian commented
Here's the features/TODO list for the PR:

- [x] add `--fast-deps` option to trigger the new install behavior
  - [ ] (optional) ensure that all possible relevant commands support `--fast-deps`
    - [x] `[node] install`
    - [x] `[node] reinstall`
    - [ ] others?  
- [x] speed up python dependency installs
  - [x] write uv-based installer
  - [x] minimize calls to subprocess/batch all possible installs
- [ ] Compile all dependencies to explicit versions before install
  - [x] pre-compile step to calculate overrides
  - [x] unified compile (core + exts)
- [ ] UI/UX for conflicts
  - [x] core-vs-extension conflicts are always settled in favor of core
  - [ ] resolve extension-vs-extension conflicts via at least one of:
    - [ ] stop, notify user of which extensions conflict (currently not possible due to upstream issue, see https://github.com/astral-sh/uv/issues/1854)
    - [ ] ask for user input, show selector with possible versions, default to latest
- [x] add special case handling 
- [ ] finalize tests

So the big remaining issues are adding some kind of extension-vs-extension conflict resolution and finishing up any tests for the new installer. Unfortunately the obvious easy path to implement ext-vs-ext behavior is a no-go; due to an upstream issue there's no way currently for us to report to the user which extensions are actually in conflict, so we can't just print out the relevant info and then tell the user to manually resolve the conflict

2024-08-11 01:52 UTC, robinjhuang requested changes

2024-08-13 03:07 UTC, telamonian commented
Okay, unittest is now functional. Said test needs a small fix tho (I realized that currently it will break whenver sympy or numpy have a new release, which is not ideal). I'll add the fix and address all of the feedback tomorrow, and then I'll merge

2024-08-13 03:45 UTC, robinjhuang commented
> Okay, unittest is now functional. Said test needs a small fix tho (I realized that currently it will break whenver sympy or numpy have a new release, which is not ideal). I'll add the fix and address all of the feedback tomorrow, and then I'll merge

Sounds great!

2024-08-15 22:07 UTC, telamonian commented on comfy_cli/command/install.py
> +        install_comfyui_dependencies(
done!

2024-08-15 22:07 UTC, telamonian commented on comfy_cli/command/install.py
> +                install_manager_dependencies(repo_dir)
and done!

2024-08-16 05:21 UTC, telamonian commented on comfy_cli/uv.py
> +    def findCoreReqs(self):
done!

2024-08-16 06:08 UTC, merged